### ISSUE TITLE
ToolFile.file_type CONTAINERFILE could be CONTAINER_FILE

### ISSUE THREAD

**Issue by redmitry** [ga4gh/tool-registry-service-schemas#100]
There are some incoherence in naming: `TEST_FILE`, but `CONTAINERFILE`.
Note that in `ToolVersion.containerfile` there is no underscore either.

Also no coherency in plurality:

```
ToolVersion.images
ToolVersion.descriptor_type
ToolVersion.verified_source
```
Cheers,

Dmitry

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TRS-26)
┆Project Name: GA4GH tool-registry-service
┆Issue Number: TRS-26

**Comment by denis-yuen** [comment]
(Left containerfile since it was meant as a bit of an homage to a Dockerfile as in https://docs.docker.com/engine/reference/builder/)
