### ISSUE TITLE
Descriptor merging (from PRC Meeting)

### ISSUE THREAD

**Issue by rishidev** [ga4gh/tool-registry-service-schemas#103]
From the first review by the PRC in the GA4GH Approval Process

In order to get all necessary information and files from a TRS server, the client needs to make quite a few requests (listed below). Would it be possible to merge c, d and e into one call? Or at least make it one call to get all descriptors.

a /tools/{id}
b /tools/{id}/versions
c /tools/{id}/versions/{version_id}/{type}/files
d /tools/{id}/versions/{version_id}/{type}/descriptor
e /tools/{id}/versions/{version_id}/{type}/descriptor/{relative_path} (one file per request, could have many files)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TRS-27)
┆containerName: GA4GH tool-registry-service
┆Issue Number: TRS-27

**Comment by denis-yuen** [comment]
In the non-standardized part of the Dockstore API, we've created (and can replicate here) a ZIP download endpoint in order to simply get everything including a file structure. 

https://dockstore.org/api/static/swagger-ui/index.html#/workflows/getWorkflowZip

Can propose this for a v2.1?
