### ISSUE TITLE
Should be able to fetch bundles with TRS API

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/tool-registry-service-schemas#116]
## Feature Request

Right now if you want to fetch a tool with **n** descriptor files via the TRS API, you need to make **n+1** API calls to fetch them all.

1. Call GET ​/tools​/{id}​/versions​/{version_id}​/{type}​/files
2. Iterate through the files in the response and fetch them one-by-one.

As workflows grow in complexity, e.g., see [gatk-sv-clinical](https://github.com/broadinstitute/gatk-sv-clinical), which has ~70 WDL files, this becomes increasingly inefficient.

It would be nice if you could fetch all the descriptors, perhaps optionally including the test parameter files, with one API call.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TRS-29)
┆containerName: GA4GH tool-registry-service
┆Issue Number: TRS-29

**Comment by denis-yuen** [comment]
How do you feel about https://github.com/ga4gh/tool-registry-service-schemas/issues/103#issuecomment-519547771 ?

**Comment by susheel** [comment]
We could add a `GET ​/tools​/{id}​/versions​/{version_id}​/{type}​/files?format=zip` for this?

**Comment by coverbeck** [comment]
> How do you feel about [#103 (comment)](https://github.com/ga4gh/tool-registry-service-schemas/issues/103#issuecomment-519547771) ?

I like @susheel's proposal.

**Comment by coverbeck** [comment]
Can we target this for 2.1?
