### ISSUE TITLE
Investigate content-type header

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/tool-registry-service-schemas#117]
Came up in https://github.com/ga4gh/cloud-interop-testing#content-type-header-misuse

Specifically, `The swagger generated server must be modified manually to make the content-type header optional.`  @pr80ik  do you happen to know which language this was encountered in?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TRS-30)
┆containerName: GA4GH tool-registry-service
┆Issue Number: TRS-30

**Comment by garyluu** [comment]
This appears to be more of a swagger-codegen issue and less of a spec issue.  https://swagger.io/docs/specification/2-0/describing-request-body/ mentions that the content type header is really only used for non-GET requests.  Looking at the swagger-ui seems to corroborate this. I generated the TRS schema using swagger codegen and python-flask and the code appears to be:
```
def tool_classes_get():  # noqa: E501
    """List all tool types

    This endpoint returns all tool-classes available.  # noqa: E501


    :rtype: List[ToolClass]
    """
    return 'do some magic!'
```
which appears to not care about content-type header at all.

Conversely, if I modify the swagger.yaml to actually require content type header, it looks like:
```
def tool_classes_get(user=None):  # noqa: E501
    """List all tool types

    This endpoint returns all tool-classes available.  # noqa: E501

    :param user: The user to create.
    :type user: dict | bytes

    :rtype: List[ToolClass]
    """
    if connexion.request.is_json:
        user = FileWrapper.from_dict(connexion.request.get_json())  # noqa: E501
    return 'do some magic!'
```

Does anyone have a set of instructions that show that content-type header is required for GET requests in the current schema?

**Comment by garyluu** [comment]
@pr80ik can you provide a more specific example?

**Comment by garyluu** [comment]
Closing until there's more concrete info available.
