### ISSUE TITLE
List tools endpoint should allow filtering by descriptor type

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/tool-registry-service-schemas#139]
The list tools endpoint, [Dockstore implementation for reference](https://dockstore.org/api/static/swagger-ui/index.html#/GA4GHV20/toolsGet), should allow filtering by descriptor type.

All platforms that I'm aware of only support one descriptor type, i.e, Terra supports only WDL, Seven Bridges only supports CWL, Galaxy only supports Galaxy. If a platform wants to fetch all tools from a TRS implementation that it can run, it has do filtering client-side, which is a mild hassle. The TRS implementation is also loading and sending back a lot more data than needed.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TRS-35)
┆containerName: GA4GH tool-registry-service
┆Issue Number: TRS-35

**Comment by coverbeck** [comment]
Further thought, we should allow multiple descriptor types, e.g., if Terra and/or Galaxy add CWL support.

Could either do it via a comma separated value, or allow the new param to appear multiple times, which http supports, and which I've never used before.

**Comment by denis-yuen** [comment]
Is there value there vs calling once for each descriptor type?

**Comment by coverbeck** [comment]
> Is there value there vs calling once for each descriptor type?

Just the fact that it would be one less call. Not crucial I suppose.

**Comment by uniqueg** [comment]
I think this can be closed?
