### ISSUE TITLE
"GET .../containerfile" endpoint should return "ImageType" as well

### ISSUE THREAD

**Issue by uniqueg** [ga4gh/tool-registry-service-schemas#155]
Currently, the `GET /tools/{id}/versions/{version_id}/containerfile` endpoint only returns a `FileWrapper` object:

```yaml
  "/tools/{id}/versions/{version_id}/containerfile":
    get:
      responses:
        "200":
          description: The tool payload.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FileWrapper"
            text/plain:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FileWrapper"
```

But I think without information on the `ImageType`, clients wouldn't know which container recipe type they are dealing with, because multiple `images` (and thus types of container recipes) can be associated with a given `ToolVersion`.

Current `FileWrapper` schema:

```yaml
    FileWrapper:
      type: object
      description: >
        [...] A containerfile is a document that describes how to build a particular
        container image. Examples include Dockerfiles for creating Docker images
        and Singularity recipes for Singularity images
      properties:
        content:
          type: string
          description: The content of the file itself. One of url or content is required.
        checksum:
          type: array
          items:
            $ref: "#/components/schemas/Checksum"
          description: "A production (immutable) tool version is required to have a
            hashcode. Not required otherwise, but might be useful to detect
            changes. "
        url:
          type: string
          description: Optional url to the underlying content, should include version
            information, and can include a git hash.  Note that this URL should
            resolve to the raw unwrapped content that would otherwise be
            available in content. One of url or content is required.
```

Current `ImageType` schema:

```yaml
    ImageType:
      type: string
      description: Indicates what kind of container is this image is.
      enum:
        - Docker
        - Singularity
        - Conda
```

Relevant part of current `ToolVersion` schema:

```yaml
    ToolVersion:
      properties:
        images:
          description: All known docker images (and versions/hashes) used by this tool. If
            the tool has to evaluate any of the docker images strings at
            runtime, those ones cannot be reported here.
          type: array
          items:
            $ref: "#/components/schemas/ImageData"
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TRS-42)
┆containerName: GA4GH tool-registry-service
┆Issue Number: TRS-42

**Comment by uniqueg** [comment]
Alternatively, for consistency with `GET /tools/{id}/versions/{version_id}/{type}/descriptor`, I suppose the endpoint could also be modified in a way that only a single `CONTAINERFILE` of a type (e.g., `Docker`) indicated in the path is returned. Perhaps that even serves a more realistic use case for clients, who, I would argue, rarely want to have recipes for different container technologies at the same time. Semantically it might perhaps unsettle some people to have `{type}` refer to two different things (containers vs. workflows) in different endpoints, but personally I think that's fine. And anyway that's a design decision that TRS has taken from the beginning on.

**Comment by denis-yuen** [comment]
Seems addressed by PR, re-open for further discussion if applicable
