### ISSUE TITLE
Upgrade TRS travis to deploy key

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/tool-registry-service-schemas#158]
Uses https://docs.travis-ci.com/user/deployment-v2/providers/pages/ dpl v2

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TRS-45)
┆containerName: GA4GH tool-registry-service
┆Issue Number: TRS-45

**Comment by garyluu** [comment]
Deemed not worth it https://github.com/garyluu/tool-registry-service-schemas/pull/1
