### ISSUE TITLE
How to refer to this in user facing documenation

### ISSUE THREAD

**Issue by mr-c** [ga4gh/tool-registry-service-schemas#17]
It gets a bit tiresome to say things like "Enable resolution using a GA4GH compliant tool registry" or the slightly more correct "Enable resolution using the GA4GH Tool Registry API"

Using just "GA4GH tool registry" implies that there is only one tool registry and that the GA4GH operates/owns it, which isn't true.

What do you all think?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TRS-11)
┆Project Name: GA4GH tool-registry-service
┆Issue Number: TRS-11

**Comment by denis-yuen** [comment]
I agree, don't have a quick answer. 
I think @briandoconnor is trying to make "TRS" a thing (along with TES and WES) ;)

Not sure that helps in this case since "Enable resolution using a TRS compatible API" or "Enable resolution using a TRS compatible registry" isn't clearly better.

**Comment by geoffjentry** [comment]
I think I agree but I'm not sure exactly what I'm agreeing to.

I definitely agree that "GA4GH tool registry" implies centrality and that's not correct. Is it just that the much more correct statements @mr-c provided are unwieldy? (I agree but don't have a better suggestion) or is it that they give the wrong impression?
