### ISSUE TITLE
Stable 2.0.1 release documentation

### ISSUE THREAD

**Issue by fbacall** [ga4gh/tool-registry-service-schemas#186]
I want to refer to the TRS version 2.0.1 docs from the `service-info` endpoint of WorkflowHub's TRS API, but the docs here:
https://ga4gh.github.io/tool-registry-service-schemas/swagger-ui/?url=../preview/release/v2.0.1/docs/web_deploy/swagger.json
are tagged with "2.0.0" in the header.

The docs under the `develop` branch: https://ga4gh.github.io/tool-registry-service-schemas/swagger-ui/?url=../preview/develop/docs/web_deploy/swagger.json refer to "2.0.1", but I assume this branch will always point to the latest release so it's probably not appropriate to link to this.

Can there be a stable link to the 2.0.1 docs that I can refer to?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TRS-51)
┆containerName: GA4GH tool-registry-service
┆Issue Number: TRS-51

**Comment by denis-yuen** [comment]
Hi,
It looks like we never got to a 2.0.1 release, so I updated the release branch from develop  2.0.1-beta.0 from the release branch for discussion 

See if 
https://ga4gh.github.io/tool-registry-service-schemas/preview/2.0.1-beta.0/docs/index.html works

Some brief description of what we have queued up after 2.0.0 here https://github.com/ga4gh/tool-registry-service-schemas/releases/tag/2.0.1-beta.0

**Comment by denis-yuen** [comment]
Late update, think I'm struggling with some issues with the documentation building system. it seems incompatible with tags in some way. 

But I've created on a branch
* https://ga4gh.github.io/tool-registry-service-schemas/swagger-ui/?url=../preview/release-2.0.1/openapi.yaml
* https://ga4gh.github.io/tool-registry-service-schemas/swagger-ui/?url=../preview/release-2.0.1/openapi.yaml

The tag itself also exists at https://github.com/ga4gh/tool-registry-service-schemas/releases/tag/2.0.1 
Hopefully that is sufficient
