### ISSUE TITLE
Propose that `ToolDescriptor.descriptor`  be removed in favor or `ToolDescriptor.url`

### ISSUE THREAD

**Issue by delagoya** [ga4gh/tool-registry-service-schemas#21]
Propose that the spec change to delete `ToolDescriptor.descriptor` since `ToolDescriptor.url` provides what is likely the canonical source for the contents of the ToolDescriptor. It would also cut down on response message size significantly.

Alternative:  make `ToolDescriptor.descriptor` optional in the response if  `ToolDescriptor.url` is provided.

**Comment by denis-yuen** [comment]
I think the alternative makes sense. 
I think the intent here was that some implementations may not be backed by a persistent URL. 
(i.e. a webservice that stores descriptors directly and isn't gathering them up like Dockstore)

**Comment by garyluu** [comment]
Doesn't look like this change was applied.  As it currently looks like:

```
 ToolDescriptor:
    type: object
    description: A tool descriptor is a metadata document that describes one or more tools.
    required:
      - type
      - descriptor
    properties:
      type:
        $ref: '#/definitions/DescriptorType'
      descriptor:
        type: string
        description: The descriptor that represents this version of the tool. (CWL or WDL)
      url:
        type: string
        description: 'Optional url to the tool descriptor used to build this image, should include version information, and can include a git hash (e.g. https://raw.githubusercontent.com/ICGC-TCGA-PanCancer/pcawg_delly_workflow/ea2a5db69bd20a42976838790bc29294df3af02b/delly_docker/Delly.cwl )'
```

which is similar to ToolDockerfile

**Comment by denis-yuen** [comment]
@garyluu  ok, let's get this in there for V2 for both
