### ISSUE TITLE
Naming issue

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/tool-registry-service-schemas#28]
Might as well mention that there is some ambiguity in the way this is named. In the terminology of https://github.com/ga4gh/workflow-execution-schemas/blob/master/Definitions.md a tool registry schema actually registers both workflows and tools. 

----------

1) A suggestion from @junjun-zhang  is possibly `functions`. Seems overloaded with functions in programming languages

2) Thing Registry Schema is tempting in that it retains the acronym. But overloaded with the amusing [Managing Things with the Thing Registry](https://docs.aws.amazon.com/iot/latest/developerguide/thing-registry.html)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TRS-9)
┆Project Name: GA4GH tool-registry-service
┆Issue Number: TRS-9

**Comment by junjun-zhang** [comment]
I weren't suggesting to use 'function'. Just find it helpful to think about it like 'function', particularly from user's point of view.

If people do want to explore other options, I personally feel 'workflow' is a good one. Or maybe 'app'?
