### ISSUE TITLE
Some comments around the API

### ISSUE THREAD

**Issue by ypriverol** [ga4gh/tool-registry-service-schemas#50]
Dear @all: 

I have some comments for the API before doing the PR: 

- [ ] In the **/api/v2/tools** entry point we shouldn't retrieve the complete tool object including the full **versions** information. We should retrieve only there the **version Ids**. In a second call the user can retrieve the the specific information of the versions by calling to this entry point **tools/{id}/versions** . This will avoid to retrieve long entry json files with almost the entire data of the registry. 

- [ ] Author should be everywhere a list of authors or maintainers. We have cases where the tools+containers are maintain by more than one author. 

- [ ] Major change: I think will be great to have an structure like the following, from my point of view we should try the following approach: 

> Tool -> ToolVersion -> ContainerImages 

The **tool** is the tool/workflow/service/ etc with a unique identifier across the entire resource. The **version** is a version of the tool (e.g. blast  2.0 ). The container image then are the final containers for each version. for example blast-2.0-python or blast-2.0-deb. This will enable our users to follow the normal release cycles of tools and versions. 

In the current approach versions + container images are collapsed in the same category. 

Minor questions: 

The features related with the checker, signed, etc can be move to a different call for those services that will provide information for it: 

"checker_url": "string",
"has_checker": true,
"signed": true,
"verified": true,
"verified_source": "string",
  
it can be something like: 

tools/{id}/verified/  

Can someone explain me the purpose of those fields? 

Best Regards 
Yasset

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TRS-7)
┆Project Name: GA4GH tool-registry-service
┆Issue Number: TRS-7

**Comment by denis-yuen** [comment]
Hi,
Thanks for commenting/working on support for TRS. 

> In the /api/v2/tools entry point we shouldn't retrieve the complete tool object including the full versions information ...  This will avoid to retrieve long entry json files with almost the entire data of the registry.

The existing solution for this is the optional support for [Github-style pagination](https://developer.github.com/v3/guides/traversing-with-pagination/). You can [limit](https://github.com/ga4gh/tool-registry-service-schemas/blob/develop/src/main/resources/swagger/ga4gh-tool-discovery.yaml#L183) the number of tools that can be returned with one call and provide links to access [different pages](https://github.com/ga4gh/tool-registry-service-schemas/blob/develop/src/main/resources/swagger/ga4gh-tool-discovery.yaml#L167) of the result. 

Does this work for your team?

> Author should be everywhere a list of authors or maintainers. We have cases where the tools+containers are maintain by more than one author.

This is reasonable with the heads-up that this might duplicate/conflict with information that is in the descriptor itself. (Yes, we already have this problem to some extent)

> In the current approach versions + container images are collapsed in the same category.

We're open to the idea as long as its optional. 

> Can someone explain me the purpose of those fields?

These fields are mostly used to support the GA4GH workflow testbed. https://docs.google.com/presentation/d/1VXdReGYXayzO7Jr-9XaLHNv6Wt46CwfvkfFDR8OEgJM/edit#slide=id.g3712cff7f5_0_99

They should all be optional (to provide workflows to the test-bed and receive feedback) and can probably be ignored for your first pass.

**Comment by ypriverol** [comment]
@denis-yuen Long time since my last comment on this. We are ready to deploy the first version of the TRS for BioContainers. One minor thing is still remaining. The current model is: 

tool -> [toolversion + container image].

We have seen that would be better to handle this in the following way: 

tool -> [toolversion] -> [container image]

Example: Let say for samtools (https://quay.io/repository/biocontainers/samtools?tab=tags) This container multiple images, and lot of then are related with same version of the tool (e.g samtools:1.5--1 and samtools:1.5--2) this is mainly because of dependency issues we also use that to generate python specific versions from conda etc. If we have one descriptor associated with samtools:1.5 that means in the current model we need to replicate again and again the same descriptor. 

Do you think is better to have the current implementation or something like: 

tool
  [ toolversion
      [container image ] 
]
Regards 
Yasset

**Comment by rishidev** [comment]
@denis-yuen - @ypriverol has been invited.

**Comment by denis-yuen** [comment]
Some of this is complete, let's continue with PRs
