### ISSUE TITLE
Home page link goes to pet store example

### ISSUE THREAD

**Issue by cjllanwarne** [ga4gh/tool-registry-service-schemas#52]
The [How to view](https://github.com/ga4gh/tool-registry-service-schemas/blob/develop/README.md#how-to-view) link on the home page is directing me to a pet store schema (ie the swagger example page)

Current link address:
http://editor.swagger.io/#/?import=https://raw.githubusercontent.com/ga4gh/tool-registry-schemas/develop/src/main/resources/swagger/ga4gh-tool-discovery.yaml

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TRS-5)
┆Project Name: GA4GH tool-registry-service
┆Issue Number: TRS-5

**Comment by denis-yuen** [comment]
(fixed in linked commit)
