### ISSUE TITLE
Upgrade TRS repo with latest auto-build ideas from WES #1912

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/tool-registry-service-schemas#60]
See https://github.com/ga4gh/dockstore/issues/1912

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TRS-3)
┆Project Name: GA4GH tool-registry-service
┆Fix Versions: TRS 1.0
┆Issue Number: TRS-3

**Comment by denis-yuen** [comment]
Also see https://github.com/ga4gh/data-repository-service-schemas/issues/194

**Comment by garyluu** [comment]
* Revert Temporary key change for forked repo
* Not have a bunch of swagger-ui, just have a bunch of links pointed to the swagger-ui which then imports the corresponding swagger-ui
