### ISSUE TITLE
GA4GH TRS Approval

### ISSUE THREAD

**Issue by cricketsloan** [ga4gh/tool-registry-service-schemas#63]
We need to monitor the TRS approval.  We also should get the tickets in here.

┆Issue is synchronized with this [Jira Epic](https://ucsc-cgl.atlassian.net/browse/TRS-1)
┆Project Name: GA4GH tool-registry-service
┆Issue Number: TRS-1

**Comment by denis-yuen** [comment]
@cricketsloan  Should be in SEAB
