### ISSUE TITLE
Documentation Process Improvements

### ISSUE THREAD

**Issue by garyluu** [ga4gh/tool-registry-service-schemas#70]
Several improvements for the documentation generation process

* Not have a bunch of swagger-ui, just have a bunch of links pointed to the swagger-ui which then imports the corresponding swagger-ui
* Fix delete script so that it handles branches with slashes in it
* Make it easier for forked repos to pass Travis.  Docs currently always change (because of timestamp) and will then require a deploy key that forked repos don't have and will fail.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TRS-12)
┆Project Name: GA4GH tool-registry-service
┆Issue Number: TRS-12

**Comment by denis-yuen** [comment]
Think this is obselete
