### ISSUE TITLE
basePath inclusion of ga4gh

### ISSUE THREAD

**Issue by rishidev** [ga4gh/tool-registry-service-schemas#71]
The basePath is currently set as 
`basePath: /api/ga4gh/v1`

There is a high level discussion if this is needed, as it might confuse with people outside genomics field.  OTOH the ga4gh means it is easily identifiable as a member of a family of tools.

After similar discussions in WES, the agreed basePath setting was 
basePath: '/ga4gh/wes/v1'
so I'd suggest the actual change would be to
basePath: '/ga4gh/trs/v2'

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TRS-13)
┆Project Name: GA4GH tool-registry-service
┆Issue Number: TRS-13

**Comment by delagoya** [comment]
+1

**Comment by denis-yuen** [comment]
+1

**Comment by denis-yuen** [comment]
I may have jumped the gun in merging this one

**Comment by rishidev** [comment]
I think this is the way to go, it is standardising to be in line with WES so there isn't really any room for manoeuvre.
