### ISSUE TITLE
Review product approval documentation

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/tool-registry-service-schemas#75]
The Product Approval Documents for TRSv2 have now been set up and are available at the following locations
[Main TRS v2 Product Approval Document](https://docs.google.com/document/d/1W2buXubJ5HbyS2tgZ7bvBmPgLVDdTCTgIngdrj2tqe8/edit#heading=h.hrg9a8447vb0)
[Security](https://docs.google.com/document/d/1Muqbo9b3UWt6zVpvlS2SyNC15RlMdTA_czLUQHm1yfw/edit)
[REWS](https://docs.google.com/document/d/1GpeexlBbkUMk-_dksvqcYbfP_RKn8fonDfgnY2lNhm8/edit)
The [GA4GH Product Approval Process Guide](https://docs.google.com/document/d/1UUJSnsPw32W5r1jaJ0vI11X0LLLygpAC9TNosjSge_w/edit#heading=h.tyqycskyykwh) has more information to the process.
Regards

@rishidev

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TRS-15)
┆Project Name: GA4GH tool-registry-service
┆Epic: GA4GH TRS Approval
┆Issue Number: TRS-15

**Comment by rishidev** [comment]
Couple of items here:

1. The implementation section has the phrase 'In other words, Dockstore launch-with for XXX is built on TRS V1' - can this be clarified to make clear where v2 sits in. Perhaps a diagram might go in here to make things clear?

2. The [introduction to TRS page](https://ga4gh.github.io/tool-registry-service-schemas/Introduction/) could probably do with some clearer explanation.

3. [REWS form needs completion](https://docs.google.com/document/d/1GpeexlBbkUMk-_dksvqcYbfP_RKn8fonDfgnY2lNhm8/edit). Although TRS is a specification it might be good to view Dockstore as an implementation in mind when answering this

4. [Security Document](https://docs.google.com/document/d/1Muqbo9b3UWt6zVpvlS2SyNC15RlMdTA_czLUQHm1yfw/edit) has some unanswered questions - may be worth putting N/A if it feels not relevant.

5. There is an issue with the Partner Engagement form that I have to look at

**Comment by rishidev** [comment]
[The Partner Engagement form link has been updated](https://docs.google.com/document/d/1ib5iSPigH6I9nA3JKdCyvuwDjMVwddQK4orFn0f6Q98/edit#heading=h.j0lsgt7eszoa)

**Comment by denis-yuen** [comment]
Update for Monday call, we've started/completed most of the items above. 
The main remaining one is improving the docs for 2) (intro to TRS page could be better)

**Comment by denis-yuen** [comment]
This has been submitted to the secretariat, closing and open more specific issues as needed
