### ISSUE TITLE
Consistent specification location for GA4GH Cloud standards

### ISSUE THREAD

**Issue by susheel** [ga4gh/tool-registry-service-schemas#81]
WES, TES & DRS stores it's specification at `/openapi/<specification_name>.swagger.yaml`. It would be great if TRS also follows the same approach to make things consistent across all the GA4GH Cloud standards.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TRS-19)
┆Project Name: GA4GH tool-registry-service
┆Epic: GA4GH TRS Approval
┆Issue Number: TRS-19

**Comment by denis-yuen** [comment]
Merged
