### ISSUE TITLE
Frozen versions of TRS spec

### ISSUE THREAD

**Issue by susheel** [ga4gh/tool-registry-service-schemas#82]
To provide backward compatibility support TRS servers/clients, we need to provide a frozen-in-time version of the spec. Suggest we keep a major-minor-version in the `/openapi` folder for the repo locked for any further edits.

`TRS v1` --> `/openapi/`**`v1`**`/tool_registry_service.swagger.yaml`
`TRS latest` --> `/openapi/tool_registry_service.swagger.yaml`

**OR**

`TRS v1` --> `/openapi/tool_registry_service.`**`v1`**`.swagger.yaml`
`TRS latest` --> `/openapi/tool_registry_service.swagger.yaml`

P.S. I would also suggest dropping `swagger` from the specification filename

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TRS-18)
┆Project Name: GA4GH tool-registry-service
┆Epic: GA4GH TRS Approval
┆Issue Number: TRS-18

**Comment by denis-yuen** [comment]
I'd be open to this, we've been using releases for this https://github.com/ga4gh/tool-registry-service-schemas/releases but this could work too. 
Do you have any mechanism in mind to lock the frozen version or would this just be by convention?

**Comment by denis-yuen** [comment]
@susheel note: I don't think the PS applies for this repo

**Comment by denis-yuen** [comment]
Merged
