### ISSUE TITLE
Confusing description for descriptor type

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/tool-registry-service-schemas#85]
The [type path parameter](https://github.com/ga4gh/tool-registry-service-schemas/blob/develop/src/main/resources/swagger/ga4gh-tool-discovery.yaml#L197) for the `/tools/{id}/versions/{version_id}/{type}/descriptor` is required, but the description implies that it is optional ("If not specified..."):

```
The output type of the descriptor. If not specified, it is up to the
underlying implementation to determine which output type to return.
Plain types return the bare descriptor while the "non-plain" types
return a descriptor wrapped with metadata. Allowable values include
"CWL", "WDL", "NFL", "PLAIN_CWL", "PLAIN_WDL", "PLAIN_NFL".
```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TRS-21)
┆Project Name: GA4GH tool-registry-service
┆Epic: GA4GH TRS Approval
┆Issue Number: TRS-21

**Comment by denis-yuen** [comment]
Looks like the description is wrong, the `required` wins.

**Comment by denis-yuen** [comment]
Merged
