### ISSUE TITLE
The /tools endpoint should allow filtering by toolClass

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/tool-registry-service-schemas#86]
The `/tools` endpoint should have a `toolclass` query parameter that filters by toolClass.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TRS-22)
┆Project Name: GA4GH tool-registry-service
┆Issue Number: TRS-22

**Comment by denis-yuen** [comment]
Merged
